services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_password
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongodb:
    image: mongo:6
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: demo_user
      MONGO_INITDB_ROOT_PASSWORD: demo_password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


volumes:
  postgres_data:
  mongo_data: