apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/configmap.yaml
  - manifests/route.yaml
  - manifests/service.yaml
  - manifests/imagestream.yaml
  - manifests/deployment.yaml