kind: ImageStream
apiVersion: image.openshift.io/v1

metadata:
  name: demoapp
  labels:
    app: demoapp
spec:
  lookupPolicy:
    local: false
  tags:
    - name: staging
      from:
        kind: DockerImage
        name: mluukkai/demoapp:staging
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local
    - name: mongo
      from:
        kind: DockerImage
        name: mluukkai/demoapp:mongo
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local
    - name: login
      from:
        kind: DockerImage
        name: mluukkai/demoapp:login
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local
    - name: oidc
      from:
        kind: DockerImage
        name: mluukkai/demoapp:oidc
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local